package:
  name: pyearth
  version: "0.2+smartleak"

source:
  git_url: https://github.com/scikit-learn-contrib/py-earth.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scikit-learn
    - pytest
    - six
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - six

test:
  requires:
    - numpy
    - scipy
    - scikit-learn
    - pytest
  imports:
    - pyearth

about:
  home: https://github.com/scikit-learn-contrib/py-earth
  license: BSD
